# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Plex Requests', max_length=255)),
                ('site_tagline', models.CharField(default="Want to watch something but it's not currently on Plex? Select an option below and do a quick search!", max_length=255)),
                ('search_movie', models.BooleanField(default=True)),
                ('search_tv', models.BooleanField(default=True)),
                ('search_music', models.BooleanField(default=True)),
                ('limit_movie', models.IntegerField(default=0)),
                ('limit_tv', models.IntegerField(default=0)),
                ('limit_music', models.IntegerField(default=0)),
                ('requests_approval', models.BooleanField(default=False)),
                ('singleton_enforce', models.IntegerField(default=1, unique=True)),
            ],
        ),
    ]
