# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20160130_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='couchpotato_api',
            field=models.CharField(default='abcd1234', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='couchpotato_directory',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='couchpotato_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='couchpotato_host',
            field=models.CharField(default='192.168.0.1', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='couchpotato_port',
            field=models.IntegerField(default=5050),
        ),
        migrations.AddField(
            model_name='config',
            name='couchpotato_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='pushbullet_api',
            field=models.CharField(default='abcd1234', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='pushbullet_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='pushover_api',
            field=models.CharField(default='abcd1234', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='pushover_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='pushover_user',
            field=models.CharField(default='abcd1234', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='sickage_port',
            field=models.IntegerField(default=8081),
        ),
        migrations.AddField(
            model_name='config',
            name='sickrage_api',
            field=models.CharField(default='abcd1234', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='sickrage_directory',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='sickrage_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='sickrage_host',
            field=models.CharField(default='192.168.0.1', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='sickrage_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='sonarr_api',
            field=models.CharField(default='abcd1234', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='sonarr_directory',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='sonarr_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='config',
            name='sonarr_host',
            field=models.CharField(default='192.168.0.1', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='sonarr_port',
            field=models.IntegerField(default=8989),
        ),
        migrations.AddField(
            model_name='config',
            name='sonarr_quality',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='config',
            name='sonarr_root',
            field=models.CharField(default='/path/to/root/tv/folder', max_length=255),
        ),
        migrations.AddField(
            model_name='config',
            name='sonarr_season_folders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='config',
            name='sonarr_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
