# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20160130_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='couchpotato_directory',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='config',
            name='sickrage_directory',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='config',
            name='sonarr_directory',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
