# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20160130_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='couchpotato_ssl',
        ),
        migrations.RemoveField(
            model_name='config',
            name='sickrage_ssl',
        ),
        migrations.RemoveField(
            model_name='config',
            name='sonarr_ssl',
        ),
        migrations.AlterField(
            model_name='config',
            name='couchpotato_host',
            field=models.CharField(default='http://192.168.0.1', max_length=255),
        ),
        migrations.AlterField(
            model_name='config',
            name='sickrage_host',
            field=models.CharField(default='http://192.168.0.1', max_length=255),
        ),
        migrations.AlterField(
            model_name='config',
            name='sonarr_host',
            field=models.CharField(default='http://192.168.0.1', max_length=255),
        ),
    ]
