# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160130_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(max_length=100),
        ),
    ]
