# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20160205_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
