# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20160205_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tmdb',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
